config/routes.rb
Rails.application.routes.draw do
  devise_for :administers, controllers: {
    sessions:      'administers/sessions',
    passwords:     'administers/passwords',
    registrations: 'administers/registrations'
  }
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions  => 'users/sessions',
   :passwords => 'users/passwords',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


namespace :administers do
	root "home#top"
	resources :users, except: [:new, :create]
	resources :reports, only: [:index, :show, :destroy]
	resources :categories, except: [:new, :show, :destroy]
end

scope module: :users do
	root "homes#top"
	get "homes/about_us" => "homes#about_us", as: "about_us_homes"
	get "users/userinfo/:id" => "users#userinfo", as: "userinfo_user"
	get "users/usertransfer/:id" => "users#usertransfer", as: "usertransfer_user"
	get "products/my_product" => "products#my_product", as: "my_product_products"
	get "tradings/bought" => "tradings#bought", as: "bought_tradings"
	get "tradings/sold" => "tradings#sold", as: "sold_tradings"
	get "tradings/barter" => "tradings#barter", as: "barter_tradings"
	get "wishlists/wish" => "wishlists#wish", as: "wish_wishlists"
	resources :users, only: [:show, :edit, :update, :create, :delete]
    resources :transfers, except: [:new, :index, :destroy]
    get "/products_search" => "products#search" ,as: "product_search"

	resources :products do
		resource :product_comments
		resource :wishlists
		resource :favorites
		resources :tradings
		resources :barter_requests, except: [:edit]
		resources :reports, only: [:new, :create]
	end

	get "requested_barter_requests/requested" => "barter_requests#requested", as: "requested_barter_requests"
	get "my_barter_requests/:user_id" => "barter_requests#my_request", as: "my_request_barter_requests"
	resources :tradings, except: [:destroy] do
		resource :trading_messages
		patch :change_payment_status
		patch :change_shipment_status
	end
end
end

app/controllers/administers/users_controller.rb
class Administers::UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to administers_root_path
    else
      render :edit
    end
  end

  def user_params
      params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :phone_number, :bank_name, :account_type, :branch_code, :account_number, :account_last_name_kana, :account_first_name_kana, :buyer_id, :seller_id, :balance, :request_amount, :is_deleted)
  end
end

app/controllers/users/barter_requests_controller.rb
class Users::BarterRequestsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @barter_request = BarterRequest.new
    @barter_requests = BarterRequest.find_by(product_id: @product.id, user_id: current_user.id)
  end

  def index
  	@product = Product.find(params[:product_id])
  	@barter_requests =  @product.barter_requests
    @barter_request = BarterRequest.find_by(user_id: current_user.id, product_id: @product.id)
  end

  def show
    @product = Product.find(params[:product_id])
    @barter_request = BarterRequest.find(params[:id])
  end

  def create
    @product = Product.find(params[:product_id])
    @barter_request = BarterRequest.new(barter_request_params)
    @barter_request.product_id = @product.id
    @barter_request.user_id = current_user.id
    @product.notice = false
    @product.save
    @barter_request.notice = false
    if @barter_request.save
      redirect_to product_barter_requests_path
    else
      render :new
    end
  end

  def update
    @barter_request = BarterRequest.find(params[:id])
    @product = Product.find(params[:product_id])
    if @product.notice == false
      @product.notice = true
      @product.save
    end
    @barter_request.update(barter_request_params)
    if @barter_request.propriety == "許可する"
      @barter_request.notice = true
      @barter_request.save
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def my_request
    @barter_requests = BarterRequest.where(user_id: params[:user_id])
  end

  def requested
    @product = Product.where(user_id: current_user.id)
    @barter_requests = BarterRequest.where(product_id: @product)
  end

  private
  def barter_request_params
    params.require(:barter_request).permit(:product_id, :user_id, :name, :image, :introduction, :comment, :product_condition, :propriety, :buyer_id, :seller_id, :notice)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController
  def create
	  @product = Product.find(params[:product_id])
    @favorite = current_user.favorites.new(product_id: @product.id)
    @favorite.save
    redirect_to request.referer
  end

  def destroy
    @product = Product.find(params[:product_id])
    @favorite = current_user.favorites.find_by(product_id: @product.id)
    @favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
	def top
	end
	def about_us
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/product_comments_controller.rb
class Users::ProductCommentsController < ApplicationController
  def create
  	@product = Product.find(params[:product_id])
  	@product_comments = @product.product_comments
	  @product_comment = current_user.product_comments.new(product_comment_params)
    @product_comment.product_id = @product.id
    @product_comment.save
    redirect_to product_path(@product)
  end

  private
  def product_comment_params
    params.require(:product_comment).permit(:comment, :user_id, :product_id)
  end
end

app/controllers/users/products_controller.rb
class Users::ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def index
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @products = @category.products.order(created_at: :desc).page(params[:page]).per(28)
      barter_requests = BarterRequest.joins(:product)
          .where(products: {category_id: params[:category_id]})
          .group(:product_id)
          .order('count(barter_requests.product_id) desc')
          .limit(5)
          .select("barter_requests.product_id, count(barter_requests.product_id) as count")
      @ranks = @category.products.find(barter_requests.pluck(:product_id))
    else
      @products = Product.all.order(created_at: :desc).page(params[:page]).per(28)
      @ranks = Product.find(BarterRequest.group(:product_id).order('count(product_id) desc').limit(5).pluck(:product_id))
    end
  end

  def show
    @product = Product.find(params[:id])
    @product_comment = ProductComment.new
    @product_comments = @product.product_comments
    @tradings = Trading.where(seller_id: @product.user.id)
    @trading = Trading.where(buyer_id: @product.user.id)
  end

  def create
    if product_params[:image].blank?
      flash[:notice] = "画像が選択されていません"
      redirect_to new_product_path
      return
    end
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    ActiveRecord::Base.transaction do
      unless @product.save
        flash[:notice] = "データの保存に失敗しました<br>"
        @product.errors.full_messages.each do |message|
          flash[:notice] << message << "<br>"
        end
        redirect_to new_product_path
        return
      end
      annotations = Vision.get_image_data(@product.image)
      if !annotations.all?{|_k, v| v == 'VERY_UNLIKELY' || v == 'UNLIKELY' || v == 'POSSIBLE'}
        raise ActiveRecord::Rollback
      end
      @product.tags.create(name: 'annotation')
    end
    if @product.postage_responsibility == "出品者負担"
      @product.price += 0
      @product.save
    else
      @product.price += @product.postage
      @product.save
    end
    if @product.persisted?
      redirect_to product_path(@product.id)
    else
      flash[:notice] = "投稿画像が有効ではありません"
      redirect_to new_product_path
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to new_product_path
    else
      render :edit
    end
  end

  def my_product
    @products = Product.where(user_id: current_user.id, sale_status: 0)
  end

  def search
    if params[:name].present?
      @products = Product.where('name LIKE ?', "%#{params[:name]}%").order(created_at: :desc).page(params[:page]).per(16)
    else
      @products = Product.all.order(created_at: :desc).page(params[:page]).per(16)
    end
  end

  private
  def product_params
    params.require(:product).permit(:category_id, :user_id, :name, :image, :introduction, :status, :price, :profit, :postage, :postage_responsibility, :sale_status, :propriety, :notice, :barter_propriety)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/reports_controller.rb
class Users::ReportsController < ApplicationController
  def new
  	@product = Product.find(params[:product_id])
  	@report = Report.new
  end

  def create
  	@product = Product.find(params[:product_id])
  	@report = Report.new(report_params)
  	@report.product_id = @product.id
    @report.user_id = current_user.id
    if @report.save
      redirect_to product_path(@product.id)
    else
      render :new
    end
  end

  private
  def report_params
    params.require(:report).permit(:product_id, :user_id, :subject, :content, :name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/trading_messages_controller.rb
class Users::TradingMessagesController < ApplicationController
  def create
  	@trading = Trading.find(params[:trading_id])
	  @trading_message = current_user.trading_messages.new(trading_message_params)
    @trading_message.trading_id = @trading.id
    @trading_message.save
    if current_user.id == @trading.seller_id
      @trading.buyer_notice = true
      @trading.seller_notice = false
      @trading.save
    else
      @trading.buyer_notice = false
      @trading.seller_notice = true
      @trading.save
    end
    redirect_to trading_path(@trading)
  end

  private
  def trading_message_params
    params.require(:trading_message).permit(:message, :user_id, :trading_id)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
	before_action :current_user, except: [:delete]

	def show
		@user = User.find(params[:id])
		@trading = Trading.where(buyer_id: @user.id)
		@tradings = Trading.where(seller_id: @user.id)
	end

	def userinfo
		@user = current_user
	end

	def usertransfer
		@user = current_user
	end

	def edit
		@user = User.find(params[:id])
		if @user.id != current_user.id
          redirect_to user_path(current_user)
        end
	end

	def update
		@user = User.find(params[:id])
		@user.update(user_params)
		if @user.request_amount == nil
		  @user.request_amount = 0
		  @user.save
		end
		if @user.balance && @user.request_amount && @user.balance >= @user.request_amount
	  	  @user.balance -= @user.request_amount
	  	end
	    current_user.save
		if @user.save
	  	  redirect_to user_path(current_user.id)
		else
		  render :show
		end
	end

  	def delete
  		user = User.find(current_user.id)
        user.is_deleted = true
        user.save
        redirect_to products_path
  	end

    private
    def user_params
    	params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :phone_number, :bank_name, :account_type, :branch_code, :account_number, :account_last_name_kana, :account_first_name_kana, :buyer_id, :seller_id, :balance, :request_amount, :image, :nickname, :introduction)
    end
end

app/controllers/users/wishlists_controller.rb
class Users::WishlistsController < ApplicationController

  def create
  	@product = Product.find(params[:product_id])
  	@wishlist = Wishlist.new(product_id: @product.id)
    @wishlist.user_id = current_user.id
    @wishlist.save
    redirect_to request.referer
  end

  def destroy
    @product = Product.find(params[:product_id])
    @wishlist = current_user.wishlists.find_by(product_id: @product.id)
    @wishlist.destroy
    redirect_to request.referer
  end

  def wish
  	@wishlists = Wishlist.where(user_id: current_user.id)
  end

  private
  def wishlist_params
    params.require(:wishlist).permit(:user_id, :product_id)
  end
end

app/helpers/administers/users_helper.rb
module Administers::UsersHelper
end

app/views/users/tradings/barter.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10">
			<h3 class="barter-list">交換取引 一覧</h3>
				<% if @tradings.blank? %>
	        		<h4 class="no-barter">交換した商品はありません</h4>
	      		<% end %>
				<% @tradings.each do |trading| %>
					<table class="table table-bordered">
						<tboy>
							<tr style="border: 2px #808080 solid;">
								<td width="10%">
									<%= link_to trading_path(trading.id) do %>
										<%= attachment_image_tag trading.product, :image, format: "jpeg", fallback: "no_image.jpg", size: "50x50" %>
									<% end %>
								</td>
								<td width="30%">
									<%= link_to trading.product.name, trading_path(trading.id) %>
								</td>
								<td width="35%">
									<% if trading.buyer_id == current_user.id && trading.payment_status == "交換(購入者)" %>
										<%= link_to "出荷(送り状番号通知)をお願いします", trading_path(trading.id), class: "btn btn-danger" %>
										<% if trading.buyer_id == current_user.id && trading.buyer_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
										<% if trading.seller_id == current_user.id && trading.seller_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
									<% elsif trading.seller_id == current_user.id && trading.shipment_status == "交換(出品者)" %>
										<%= link_to "出荷(送り状番号通知)をお願いします", trading_path(trading.id), class: "btn btn-danger" %>
										<% if trading.buyer_id == current_user.id && trading.buyer_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
										<% if trading.seller_id == current_user.id && trading.seller_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
									<% end %>
									<% if trading.buyer_id == current_user.id && trading.payment_status == "番号確認完了(購入者)" %>
										<%= link_to "交換者の評価をお願いします", trading_path(trading.id), class: "btn btn-danger" %>
										<% if trading.buyer_id == current_user.id && trading.buyer_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
										<% if trading.seller_id == current_user.id && trading.seller_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
									<% elsif trading.seller_id == current_user.id && trading.shipment_status == "番号確認完了(出品者)" %>
										<%= link_to "交換者の評価をお願いします", trading_path(trading.id), class: "btn btn-danger" %>
										<% if trading.buyer_id == current_user.id && trading.buyer_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
										<% if trading.seller_id == current_user.id && trading.seller_notice == true %>
											<div><%= link_to "メッセージがきています", trading_path(trading.id) %></div>
										<% end %>
									<% end %>
									<% if trading.buyer_id == current_user.id && trading.payment_status == "交換お疲れ様でした(購入者)" %>
					　　					<%= link_to "取引済", trading_path(trading.id), class: "btn btn-default" %>
									<% elsif trading.seller_id == current_user.id && trading.shipment_status == "交換お疲れ様でした(出品者)" %>
					　　					<%= link_to "取引済", trading_path(trading.id), class: "btn btn-default" %>
									<% end %>
								</td>
								<td width="20%">
									<%= trading.product.created_at.strftime('%Y-%m-%d') %>
								</td>
							</tr>
						</tboy>
					</table>
				<% end %>
		</div>
	</div>
</div>

app/views/users/tradings/bought.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10">
			<h3 class="bought-list">購入取引 一覧</h3>
				<% if @tradings.blank? %>
	        		<h4 class="no-bought">購入した商品はありません</h4>
	      		<% end %>
					<% @tradings.each do |trading| %>
						<table class="table table-bordered">
							<tboy>
								<tr style="border: 2px #808080 solid;">
									<td width="10%">
										<%= link_to trading_path(trading.id) do %>
											<%= attachment_image_tag trading.product, :image, format: "jpeg", fallback: "no_image.jpg", size: "50x50" %>
										<% end %>
									</td>
									<td width="30%">
										<%= link_to trading.product.name, trading_path(trading.id) %>
									</td>
									<td width="15%">
										<%= number_to_currency(trading.product.price, :unit => "￥", :precision => 0) %>
									</td>
									<td width="25%">
										<% if trading.buyer_id == current_user.id && trading.payment_status == "出品者へ入金報告をする" %>
											<%= link_to "入金してください", trading_path(trading.id), class: "btn btn-danger" %>
											<% if trading.buyer_id == current_user.id && trading.buyer_notice == true %>
													<div><%= link_to "メッセージがきています", trading_path(trading.id), :style=>"font-weight:bold; color:orange" %></div>
											<% end %>
										<% end %>
										<% if trading.buyer_id == current_user.id && trading.payment_status == "入金報告をしました。出品者の発送待ちです" %>
											<%= link_to "発送待ち", trading_path(trading.id), class: "btn btn-info" %>
											<% if trading.buyer_id == current_user.id && trading.buyer_notice == true %>
													<div><%= link_to "メッセージがきています", trading_path(trading.id), :style=>"font-weight:bold; color:orange" %></div>
											<% end %>
										<% end %>
										<% if trading.buyer_id == current_user.id && trading.payment_status == "受取報告をする" %>
						　　					<%= link_to "商品到着後、受取評価してください", trading_path(trading.id), class: "btn btn-danger" %>
											<% if trading.buyer_id == current_user.id && trading.buyer_notice == true %>
													<div><%= link_to "メッセージがきています", trading_path(trading.id), :style=>"font-weight:bold; color:orange" %></div>
											<% end %>
										<% end %>
										<% if trading.buyer_id == current_user.id && trading.payment_status == "ご利用誠にありがとうございました！" %>
						　　					<%= link_to "取引済", trading_path(trading.id), class: "btn btn-default" %>
										<% end %>
									</td>
									<td width="20%">
										<%= trading.product.created_at.strftime('%Y-%m-%d') %>
									</td>
								</tr>
							</tboy>
						</table>
					<% end %>
		</div>
	</div>
</div>

app/views/users/tradings/new.html.erb
<div class="container">
  <div class="row">
      <div class="col-xs-10">
        <h2 class="order-confirm">
          <% if @barter_request && @barter_request.propriety == "許可する" %>
            <%= "交換取引 確定画面" %>
          <% else %>
            <%= "購入内容の確認" %>
          <% end %>
        </h2>
          <table class="table table-bordered">
            <tboy>
              <tr>
                <td>
                  <%= attachment_image_tag @product, :image, format: "jpeg", fallback: "no_image.jpg", size: "130x130", class: "center-block" %>
                  <% unless @barter_request && @barter_request.propriety == "許可する" %>
                    <h3>合計金額 <%= number_to_currency(@product.price, :unit => "￥", :precision => 0) %></h3>
                      <button type="button" class="btn btn-secondary col-xs-2" style="font-weight:bold; background: #999999;">
                      送料 / <%= @product.postage_responsibility %>
                      </button>
                  <% end %>
                </td>
              </tr>
              <%= form_for(@trading, url: product_tradings_path(@product)) do |f| %>
                <%= f.hidden_field :seller_id, :value => @product.user.id %>
                <%= f.hidden_field :buyer_id, :value => current_user.id %>
              <% unless @barter_request && @barter_request.propriety == "許可する" %>
              <tr>
                <td>
                  <%= f.label :"支払方法", class: "col-xs-12" %>
                  <%= f.select :paymethod, [["クレジットカード"], ["コンビニ払い"]], class: "col-xs-8" %>
                </td>
              </tr>
              <% end %>
              <tr>
                <td>
                  <div class="col-xs-3">お届け先</div>
                  <%= current_user.prefecture_code %><%= current_user.address_city %><%= current_user.address_street %>
                </td>
              </tr>
              <tr>
                <td>
                  <% if @barter_request && @barter_request.propriety == "許可する" %>
                    <%= f.hidden_field :paymethod, :value => "交換" %>
                    <%= f.submit "交換取引を確定する", {method: :post, class: "btn-sm btn-success col-xs-12", params:{product_id: @product.id, seller_id: @product.user.id}} %>
                  <% else %>
                    <%= f.submit "購入を確定する", {method: :post, class: "btn-sm btn-danger col-xs-12", params:{product_id: @product.id, seller_id: @product.user.id}} %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tboy>
          </table>
      </div>
  </div>
</div>