config/routes.rb
Rails.application.routes.draw do
  devise_for :administers, controllers: {
    sessions:      'administers/sessions',
    passwords:     'administers/passwords',
    registrations: 'administers/registrations'
  }
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions  => 'users/sessions',
   :passwords => 'users/passwords',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


namespace :administers do
	root "home#top"
	resources :users, except: [:new, :create]
	resources :reports, only: [:index, :show, :destroy]
	resources :categories, except: [:new, :show, :destroy]
end

scope module: :users do
	root "homes#top"
	get "homes/about_us" => "homes#about_us", as: "about_us_homes"
	get "users/userinfo/:id" => "users#userinfo", as: "userinfo_user"
	get "users/usertransfer/:id" => "users#usertransfer", as: "usertransfer_user"
	get "products/my_product" => "products#my_product", as: "my_product_products"
	get "tradings/bought" => "tradings#bought", as: "bought_tradings"
	get "tradings/sold" => "tradings#sold", as: "sold_tradings"
	get "tradings/barter" => "tradings#barter", as: "barter_tradings"
	get "wishlists/wish" => "wishlists#wish", as: "wish_wishlists"
	resources :users, only: [:show, :edit, :update, :create, :delete]
    resources :transfers, except: [:new, :index, :destroy]
    get "/products_search" => "products#search" ,as: "product_search"

	resources :products do
		resource :product_comments
		resource :wishlists
		resource :favorites
		resources :tradings
		resources :barter_requests, except: [:edit]
		resources :reports, only: [:new, :create]
	end

	get "requested_barter_requests/requested" => "barter_requests#requested", as: "requested_barter_requests"
	get "my_barter_requests/:user_id" => "barter_requests#my_request", as: "my_request_barter_requests"
	resources :tradings, except: [:destroy] do
		resource :trading_messages
		patch :change_payment_status
		patch :change_shipment_status
	end
end
end

app/models/administer.rb
class Administer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/barter_request.rb
class BarterRequest < ApplicationRecord
  belongs_to :user
  belongs_to :product
  attachment :image
  enum product_condition:{
  "新品・未使用": 0,
  "未使用に近い": 1,
  "目立った傷や汚れ無し": 2,
  "傷や汚れあり": 3,
  "全体的に状態が悪い": 4
  }
  enum propriety:{
    "許可しない": false,
    "許可する": true
  }
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
	has_many :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	attachment :image

	def postage
		postage = 1000
	end

  def favorited_by?(user)
    if user
      favorites.where(user_id: user.id).exists?
    else
      return nil
    end
  end

  def wished_by?(user)
    if user
      wishlists.where(user_id: user.id).exists?
    else
      return nil
    end
  end

	enum status:{
    "新品・未使用": 0,
    "未使用に近い": 1,
    "目立った傷や汚れ無し": 2,
    "傷や汚れあり": 3,
    "全体的に状態が悪い": 4
  }

	enum postage_responsibility:{
    "出品者負担": 0,
    "購入者負担": 1
  }
  enum sale_status:{
    "販売中": 0,
    "売り切れ": 1,
    "交換済": 2
  }
  enum propriety:{
    "交換不可": 0,
    "交換可能": 1
  }
  has_one :trading, autosave: true, dependent: :destroy
  belongs_to :user
  belongs_to :category
  has_many :barter_requests
  has_many :favorites, dependent: :destroy
  has_many :reports
  has_many :wishlists
  has_many :product_comments
  has_many :tags

  validates :image, presence: true
  validates :name, presence: true
  validates :category_id, presence: true, allow_blank: true
  validates :status, presence: true
  validates :price, presence: true
  validates :postage_responsibility, presence: true

  private
    def build_child
      build_trading
    end
end

app/models/product_comment.rb
class ProductComment < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/models/report.rb
class Report < ApplicationRecord
  enum subject:{
    "偽造品・レプリカ商品": 0,
	"公序良俗に反する商品": 1,
	"知的財産権(著作権・商標権など)侵害商品": 2,
	"その他法令違反": 3
}
  belongs_to :user
  belongs_to :product
end

app/models/tag.rb
class Tag < ApplicationRecord
	belongs_to :product
end

app/models/trading.rb
class Trading < ApplicationRecord
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
  belongs_to :product
  belongs_to :user
  has_many :trading_messages

  enum paymethod:{
   "クレジットカード": 0,
   "コンビニ払い": 1,
   "交換": 2
  }
  enum payment_status:{
   "出品者へ入金報告をする": 0,
   "入金報告をしました。出品者の発送待ちです": 1,
   "受取報告をする": 2,
   "ご利用誠にありがとうございました！": 3,
   "交換(購入者)": 4,
   "番号確認完了(購入者)": 5,
   "交換お疲れ様でした(購入者)": 6
  }
  enum shipment_status:{
   "出荷報告をする": 0,
   "出荷を通知しました。購入者の評価待ちです": 1,
   "購入者を評価する": 2,
   "取引完了": 3,
   "交換(出品者)": 4,
   "番号確認完了(出品者)": 5,
   "交換お疲れ様でした(出品者)": 6
  }
end

app/models/trading_message.rb
class TradingMessage < ApplicationRecord
	belongs_to :user
	belongs_to :trading
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  enum is_deleted:{
    "有効": false,
    "無効": true
  }
  def active_for_authentication?
      super && self.is_deleted != "無効"
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :image
  has_many :products
  has_many :active_tradings, class_name: "Trading", foreign_key: :buyer_id
  has_many :buyers, through: :active_relationships, source: :seller
  has_many :passive_tradings, class_name: "Trading", foreign_key: :seller_id
  has_many :sellers, through: :passive_relationships, source: :buyer
  has_many :barter_requests
  has_many :favorites, dependent: :destroy
  has_many :tradings
  has_many :reports
  has_many :wishlists
  has_many :trading_messages
  has_many :product_comments

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :nickname, presence: true
  validates :postcode, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true
  validates :phone_number, presence: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
	belongs_to :user
	belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :prefecture_code, :address_city, :address_street, :address_building, :phone_number, :email, :nickname])
  end
  def after_sign_in_path_for(resource_or_scope)
  	if resource_or_scope.is_a?(Administer)
      administers_root_path
    else
      user_path(current_user)
    end
  end
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :administer
      new_administer_session_path
    else
      root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/favorites_helper.rb
module Users::FavoritesHelper
end

app/helpers/users/homes_helper.rb
module Users::HomesHelper
end

app/helpers/users/products_helper.rb
module Users::ProductsHelper
end

app/helpers/users/reports_helper.rb
module Users::ReportsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top" style="background-color:#f79428;">
      <nav class="nav navbar-nav navbar-left">
          <span class="glyphicon glyphicon-star" aria-hidden="true" style="font-size: 11px"></span>
          <span class="glyphicon glyphicon-star" aria-hidden="true" style="font-size: 11px"></span>
          <%= link_to root_path do %>
              <span class="title">カランド</span>
          <% end %>
          <span class="glyphicon glyphicon-star" aria-hidden="true" style="font-size: 8px"></span>
          <span class="glyphicon glyphicon-star" aria-hidden="true" style="font-size: 8px"></span>
      </nav>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-center">
          <span class="search">
            <%= form_with url: product_search_path, method: :get, data: {remote: false} do |f| %>
              <%= f.text_field :name , placeholder: "何をお探しですか？"%>
          </span>
            <button type="submit" class="btn btn-default glyphicon glyphicon-zoom-in"></button>
            <% end %>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              カテゴリーからもお探しできます
            <span class="caret"></span>
            </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "全て", products_path %>
          </li>
          <li>
            <% Category.all.each do |category| %>
          </li>
          <li>
            <%= link_to category.name, products_path(category_id: category.id) %>
          </li>
            <% end %>
        </ul>
          </div>
        </ul>
      <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? && !request.fullpath.include?("administers") %>
            <% if BarterRequest.where(buyer_id: current_user.id, notice: true).count != 0 %>
              <div class="alert alert-info" role="alert"><%= link_to "リクエストが許可されました", my_request_barter_requests_path(current_user.id) %></div>
            <% end %>
            <% if Product.where(user_id: current_user.id, notice: false).count != 0 %>
              <div class="alert alert-info" role="alert"><%= link_to "交換リクエストがきています　内容を覗いてみましょう", requested_barter_requests_path %></div>
            <% end %>
            <% if Trading.where(buyer_id: current_user.id, buyer_notice: true).where("(payment_status = ?) OR (payment_status = ?) OR (payment_status = ?) ", 0, 1, 2) .count != 0 %>
              <div class="alert alert-info" role="alert"><%= link_to "出品者よりメッセージがあります", bought_tradings_path %></div>
            <% end %>
            <% if Trading.where(seller_id: current_user.id, seller_notice: true).where("(shipment_status = ?) OR (shipment_status = ?) OR (shipment_status = ?) ", 0, 1, 2) .count != 0 %>
               <div class="alert alert-info" role="alert"><%= link_to "購入者よりメッセージがあります", sold_tradings_path %> </div>
            <% end %>
            <% if Trading.where(buyer_id: current_user.id, buyer_notice: true).where("(payment_status = ?) OR (payment_status = ?) ", 4, 5) .count != 0 %>
              <div class="alert alert-info" role="alert"><%= link_to "交換者よりメッセージがあります", barter_tradings_path %></div>
            <% end %>
            <% if Trading.where(seller_id: current_user.id, seller_notice: true).where("(shipment_status = ?) OR (shipment_status = ?) ", 4, 5) .count != 0 %>
              <div class="alert alert-info" role="alert"><%= link_to "交換者よりメッセージがあります", barter_tradings_path %>
            <% end %>
              </div>
            <% if Trading.where(seller_id: current_user.id, payment_status: "出品者へ入金報告をする").count != 0 %>
              <div class="alert alert-info" role="alert"><%= link_to "商品が購入されました　入金を待っています", sold_tradings_path %>
            <% end %></div>
            <li class="wishlists"><%= link_to "ほしいものリスト", wish_wishlists_path %></li>
            <li>
              <span class="trading-list">
                <%= link_to "買った！", bought_tradings_path %>
                  <% if Trading.where("(payment_status = ?) OR (payment_status = ?) ", 0, 2).where("(paymethod = ?) OR (paymethod = ?) ", 0, 1).where(buyer_id: current_user.id).count == 0 %>
                    <span class="badge1">
                      <span class="badge", style="color: white;">
                        <%= Trading.where("(payment_status = ?) OR (payment_status = ?) ", 0, 2).where("(paymethod = ?) OR (paymethod = ?) ", 0, 1).where(buyer_id: current_user.id).count %>
                      </span>
                    </span>
                  <% else %>
                    <span class="badge2">
                      <span class="badge", style="color: white;">
                        <%= Trading.where("(payment_status = ?) OR (payment_status = ?) ", 0, 2).where("(paymethod = ?) OR (paymethod = ?) ", 0, 1).where(buyer_id: current_user.id).count %>
                      </span>
                    </span>
                  <% end %>
              </span>
            </li>
            <li>
              <span class="trading-list">
                <%= link_to "売れた！", sold_tradings_path %>
                  <% if Trading.where("(payment_status = ?) OR (shipment_status = ?) ", 1, 2).where("(paymethod = ?) OR (paymethod = ?) ", 0, 1).where(seller_id: current_user.id).count == 0 %>
                    <span class="badge3">
                      <span class="badge", style="color: white;">
                        <%= Trading.where("(payment_status = ?) OR (shipment_status = ?) ", 1, 2,).where("(paymethod = ?) OR (paymethod = ?) ", 0, 1).where(seller_id: current_user.id).count %>
                      </span>
                    </span>
                  <% else %>
                    <span class="badge4">
                      <span class="badge", style="color: white;">
                        <%= Trading.where("(payment_status = ?) OR (shipment_status = ?) ", 1, 2).where("(paymethod = ?) OR (paymethod = ?) ", 0, 1).where(seller_id: current_user.id).count %>
                      </span>
                    </span>
                  <% end %>
              </span>
            </li>
            <li>
              <span class="trading-list">
                <%= link_to "交換！", barter_tradings_path %>
                  <% if Trading.where("((payment_status = ?)OR(shipment_status = ?)) OR ((payment_status = ?) OR (shipment_status = ?))", 4, 4, 5, 5).where("((buyer_id = ?)OR(seller_id = ?))", current_user.id, current_user.id).count == 0 %>
                    <span class="badge3">
                      <span class="badge", style="color: white;">
                        <%= Trading.where("((payment_status = ?)OR(shipment_status = ?)) OR ((payment_status = ?) OR (shipment_status = ?))", 4, 4, 5, 5).where("((buyer_id = ?)OR(seller_id = ?))", current_user.id, current_user.id).count %>
                      </span>
                    </span>
                  <% else %>
                    <span class="badge4">
                      <span class="badge", style="color: white;">
                        <%= Trading.where("((payment_status = ?)OR(shipment_status = ?)) OR ((payment_status = ?) OR (shipment_status = ?))", 4, 4, 5, 5).where("((buyer_id = ?)OR(seller_id = ?))", current_user.id, current_user.id).count %>
                      </span>
                    </span>
                  <% end %>
              </span>
            </li>
            <li class="mypage"><%= link_to "マイページ", user_path(current_user) %></li>
          <% elsif administer_signed_in? && request.fullpath.include?("administers") %>
            <ul class="nav navbar-nav navbar-right">
              <li class="administer-menu"><%= link_to "通報", administers_reports_path %></li>
              <li class="administer-menu"><%= link_to "カテゴリー", administers_categories_path %></li>
              <li class="administer-sign_out"><%= link_to "ログアウト", destroy_administer_session_path, method: :delete, :style=>"color:black;" %></li>
            </ul>
          <% elsif request.fullpath.include?("administers") %>
            <ul class="nav navbar-nav navbar-right">
              <li class="sign_in"><%= link_to '管理者ログイン', new_administer_session_path %></li>
              <li class="sign_up"><%= link_to '新メンバー登録', new_administer_registration_path %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li class="about_us"><%= link_to 'カランドって何？', about_us_homes_path %></li>
              <li class="sign_in"><%= link_to 'ログイン', new_user_session_path %></li>
              <li class="sign_up"><%= link_to '新規会員登録', new_user_registration_path %></li>
            </ul>
          <% end %>
    </header>
    <%= yield %>
  </body>
</html>